language: go
go:
  - 1.0
  - 1.1
  - 1.1.2
  - 1.2
  - 1.2.1
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
branches:
  only:
    - master
install: true
before_script:
  - travis_retry go get -v -x github.com/kwilczynski/container/stack
script: go test -v -x ./... -run '^Test.*'
