language: go
go:
  - 1.0
  - 1.1
  - 1.2
  - tip
matrix:
  allow_failures:
    - go: tip
branches:
  only:
    - master
install: true
before_script:
  - go get -v -x github.com/kwilczynski/container/stack
script: go test -v -x ./... -run '^Test.*'
